import CA from './AC.png'
import DA from './AD.png'
import HA from './AH.png'
import SA from './AS.png'
import C2 from './2C.png'
import D2 from './2D.png'
import H2 from './2H.png'
import S2 from './2S.png'
import C3 from './3C.png'
import D3 from './3D.png'
import H3 from './3H.png'
import S3 from './3S.png'
import C4 from './4C.png'
import D4 from './4D.png'
import H4 from './4H.png'
import S4 from './4S.png'
import C5 from './5C.png'
import D5 from './5D.png'
import H5 from './5H.png'
import S5 from './5S.png'
import C6 from './6C.png'
import D6 from './6D.png'
import H6 from './6H.png'
import S6 from './6S.png'
import C7 from './7C.png'
import D7 from './7D.png'
import H7 from './7H.png'
import S7 from './7S.png'
import C8 from './8C.png'
import D8 from './8D.png'
import H8 from './8H.png'
import S8 from './8S.png'
import C9 from './9C.png'
import D9 from './9D.png'
import H9 from './9H.png'
import S9 from './9S.png'
import C10 from './10C.png'
import D10 from './10D.png'
import H10 from './10H.png'
import S10 from './10S.png'
import CJ from './JC.png'
import DJ from './JD.png'
import HJ from './JH.png'
import SJ from './JS.png'
import CQ from './QC.png'
import DQ from './QD.png'
import HQ from './QH.png'
import SQ from './QS.png'
import CK from './KC.png'
import DK from './KD.png'
import HK from './KH.png'
import SK from './KS.png'

// suit:num


const cardFront = [
    {id: 0, src: CA},
    {id: 1, src: DA},
    {id: 2, src: HA},
    {id: 3, src: SA},
    {id: 4, src: C2},
    {id: 5, src: D2},
    {id: 6, src: H2},
    {id: 7, src: S2},
    {id: 8, src: C3},
    {id: 9, src: D3},
    {id: 10, src: H3},
    {id: 11, src: S3},
    {id: 12, src: C4},
    {id: 13, src: D4},
    {id: 14, src: H4},
    {id: 15, src: S4},
    {id: 16, src: C5},
    {id: 17, src: D5},
    {id: 18, src: H5},
    {id: 19, src: S5},
    {id: 20, src: C6},
    {id: 21, src: D6},
    {id: 22, src: H6},
    {id: 23, src: S6},
    {id: 24, src: C7},
    {id: 25, src: D7},
    {id: 26, src: H7},
    {id: 27, src: S7},
    {id: 28, src: C8},
    {id: 29, src: D8},
    {id: 30, src: H8},
    {id: 31, src: S8},
    {id: 32, src: C9},
    {id: 33, src: D9},
    {id: 34, src: H9},
    {id: 35, src: S9},
    {id: 36, src: C10},
    {id: 37, src: D10},
    {id: 38, src: H10},
    {id: 39, src: S10},
    {id: 40, src: CJ},
    {id: 41, src: DJ},
    {id: 42, src: HJ},
    {id: 43, src: SJ},
    {id: 44, src: CQ},
    {id: 45, src: DQ},
    {id: 46, src: HQ},
    {id: 47, src: SQ},
    {id: 48, src: CK},
    {id: 49, src: DK},
    {id: 50, src: HK},
    {id: 51, src: SK}
]

export default cardFront;